---
title: "Replication of Study \"How Quick Decisions Illuminate Moral Character\" by Critcher et al. (2013, Social Psychological and Personality Science)"
author: "Asad Tariq (astariq@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  pdf:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

<!-- [No abstract is needed.]  Each replication project will have a straightforward, no frills report of the study and results.  These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of data collection.  Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for replication, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.   -->

This experiment focuses on the way the morality of person's character is ascertained in relation to the speed with which they make decisions and I chose to replicate it because I was interested in learning about how psychology, and the way the human brain behaves, can shape how people are perceived in a social setting based on their decisions even before they have begun to act upon them. My interests also lie in the domain of human social networks and I was curious about whether, within these dynamic networks, the people linked with each other have some similar form of judging each other's characteristics including morality before establishing links or not and therefore I opted for experiment 1 of this study.

In order to replicate experiment 1 of this study, we will need a sample size of around 100-120 participants who will read up on a hypothetical scenario explaining to them two accompanying actions/outcomes: the first being a moral one and the other being an immoral one. The two actors involved in the scenario will differ by nature - one of them will be "quick" to act, while the other will be "slow". The participants will read the given scenario and answer some questions immediately afterwards. The questions will revolve around 4 different categories, namely: quickness, moral character evaluation, certainty and emotional impulsivity, which the participants will answer on a scale from 1-7.

A potential challenge will be to gather a large enough sample size of participants similar to the original study (the original study had 119 participants in experiment 1) which are either undergraduates or from a similar community to conduct the replication of the experiment. Another challenge would be to establish a reliable way to measure the quickness of judgement and the moral character of the actors involved in the scenario, such that the participants are consistent with their responses across different conditions. Yet another challenge would be the way in which to convey the notion of "quick" and "slow" as is intended in this particular study so that there is no consequential bias in the evaluations of assessed morality of the two actors.

[GitHub Repository](https://github.com/Asad-Tariq/critcher2013)

[Link to original paper](https://github.com/Asad-Tariq/critcher2013/blob/main/original_paper/Critcher_et_al_2013.pdf)

## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
